jobs:
- job: Android_CI
  pool:
    vmImage: 'macOS-10.14'
  steps:
    - script: pip install cmake==3.17.1 && alias cmake=/usr/local/bin/cmake && cmake --version && brew install coreutils
      displayName: Install cmake 3.17.1 and coreutils
    - script: 'git submodule update --init --recursive --progress'
      displayName: Clone submodules
    - script: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'ndk-bundle'
      displayName: Install Android NDK
    - script: tools/ci_build/build.py --android --build_dir build --android_sdk_path $ANDROID_HOME --android_ndk_path $ANDROID_HOME/ndk-bundle --android_abi=x86_64 --skip_submodule_sync --parallel --use_nnapi
      displayName: Build and Test on Android Emulator

